'use strict';const DEFAULT_VOLUME=.5;var FADE_TIME=.25;const FADE_SET_TARGET_TIME_CONSTANT=.05,MIN_FREQ=1,MAX_FREQ=20154,MIN_PIANO_KEY=1,MAX_PIANO_KEY=99,FIRST_C=4,NOTE_NAMES=";A0 Dbl Pedal A;A\u266f0\u2009/\u2009B\u266d0;B0;C1 Pedal C;C\u266f1\u2009/\u2009D\u266d1;D1;D\u266f1\u2009/\u2009E\u266d1;E1;F1;F\u266f1\u2009/\u2009G\u266d1;G1;G\u266f1\u2009/\u2009A\u266d1;A1;A\u266f1\u2009/\u2009B\u266d1;B1;C2 Deep C;C\u266f2\u2009/\u2009D\u266d2;D2;D\u266f2\u2009/\u2009E\u266d2;E2;F2;F\u266f2\u2009/\u2009G\u266d2;G2;G\u266f2\u2009/\u2009A\u266d2;A2;A\u266f2\u2009/\u2009B\u266d2;B2;C3 Tenor C;C\u266f3\u2009/\u2009D\u266d3;D3;D\u266f3\u2009/\u2009E\u266d3;E3;F3;F\u266f3\u2009/\u2009G\u266d3;G3;G\u266f3\u2009/\u2009A\u266d3;A3;A\u266f3\u2009/\u2009B\u266d3;B3;C4 Middle C;C\u266f4\u2009/\u2009D\u266d4;D4;D\u266f4\u2009/\u2009E\u266d4;E4;F4;F\u266f4\u2009/\u2009G\u266d4;G4;G\u266f4\u2009/\u2009A\u266d4;A4;A\u266f4\u2009/\u2009B\u266d4;B4;C5;C\u266f5\u2009/\u2009D\u266d5;D5;D\u266f5\u2009/\u2009E\u266d5;E5;F5;F\u266f5\u2009/\u2009G\u266d5;G5;G\u266f5\u2009/\u2009A\u266d5;A5;A\u266f5\u2009/\u2009B\u266d5;B5;C6 Soprano C;C\u266f6\u2009/\u2009D\u266d6;D6;D\u266f6\u2009/\u2009E\u266d6;E6;F6;F\u266f6\u2009/\u2009G\u266d6;G6;G\u266f6\u2009/\u2009A\u266d6;A6;A\u266f6\u2009/\u2009B\u266d6;B6;C7 Dbl high C;C\u266f7\u2009/\u2009D\u266d7;D7;D\u266f7\u2009/\u2009E\u266d7;E7;F7;F\u266f7\u2009/\u2009G\u266d7;G7;G\u266f7\u2009/\u2009A\u266d7;A7;A\u266f7\u2009/\u2009B\u266d7;B7;C8;C\u266f8\u2009/\u2009D\u266d8;D8;D\u266f8\u2009/\u2009E\u266d8;E8;F8;F\u266f8\u2009/\u2009G\u266d8;G8;G\u266f8\u2009/\u2009A\u266d8;A8;A\u266f8\u2009/\u2009B\u266d8;B8".split(";");
function reflow(){}
var BrowserDetect={init:function(){this.identifyBrowser();if("Explorer"==this.browser){if(this.IE=!0,8>=this.majorVersion||8===document.documentMode)this.IE8=!0}else"Firefox"==this.browser?this.Firefox=!0:"Chrome"==this.browser?this.Chrome=!0:"Safari"==this.browser?this.Safari=!0:"Edge"==this.browser?this.Edge=!0:"Opera"==this.browser&&(this.Opera=!0);this.supportsClipboardWriting=document.queryCommandSupported("copy");this.identifyOS();"Windows"==this.OS?this.Windows=!0:"iOS"==this.OS?this.iOS=!0:
"MacOS"==this.OS&&(this.MacOS=!0)},identifyBrowser:function(){for(var a=0;a<this.dataBrowser.length;a++){var c=this.dataBrowser[a];if(-1!=(c.string||navigator.userAgent).indexOf(c.subString)){this.browser=c.identity;a=c.versionSearch||c.subString;(c=this.searchVersion(navigator.userAgent,a))?(this.version=c,this.majorVersion=Math.floor(c)):(c=this.searchVersion(navigator.appVersion,a))?(this.version=c,this.majorVersion=Math.floor(c)):this.majorVersion=this.version="Unknown";return}}this.version=this.browser=
"Unknown"},identifyOS:function(){for(var a=0;a<this.dataOS.length;a++)if(-1!=this.dataOS[a].string.indexOf(this.dataOS[a].subString)){this.OS=this.dataOS[a].identity;return}this.OS="Unknown"},searchVersion:function(a,c){var b;return-1!=(b=a.indexOf(c))?parseFloat(a.substring(b+c.length+1)):null},dataBrowser:[{subString:"Opera",identity:"Opera"},{subString:"OPR",identity:"Opera"},{subString:"Edge",identity:"Edge"},{subString:"MSIE",identity:"Explorer"},{subString:"Trident",identity:"Explorer",versionSearch:"rv"},
{subString:"Firefox",identity:"Firefox"},{subString:"Chrome",identity:"Chrome"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{subString:"Apple",identity:"Safari",versionSearch:"Version"}],dataOS:[{string:navigator.platform,subString:"Mac",identity:"MacOS"},{string:navigator.platform,subString:"iPad",identity:"iOS"},{string:navigator.platform,subString:"iPhone",identity:"iOS"},{string:navigator.platform,subString:"iPod",identity:"iOS"},{string:navigator.userAgent,
subString:"Android",identity:"Android"},{string:navigator.userAgent,subString:"android",identity:"Android"},{string:navigator.platform,subString:"Linux",identity:"Linux"},{string:navigator.platform,subString:"Win",identity:"Windows"}]};BrowserDetect.init();function setCookie(a,c,b,d){b=b?"; path="+b:"";if(d){var e=new Date;e.setTime(e.getTime()+864E5*d);d="; expires="+e.toGMTString()}else d="";document.cookie=a+"="+encodeURIComponent(c)+d+b;cachedCookies&&(cachedCookies[a]=c)}
function loadCookies(){if(window.cachedCookies)return!1;window.cachedCookies={};if(0<document.cookie.length)for(var a=document.cookie.split("; "),c=0;c<a.length;c++){var b=a[c].indexOf("="),d=a[c].substring(0,b);cachedCookies[d]=decodeURIComponent(a[c].substring(b+1))}}function getCookie(a){return cachedCookies[a]?cachedCookies[a]:null}function deleteCookie(a,c){void 0===c&&(c="/");setCookie(a,"",c,-1);delete cachedCookies[a]}
function writeCookieMessage(a,c,b){getCookie("cOK")||(window.onCookieConsent=function(){document.getElementById("cookie-message").style.display="none";setCookie("cOK","y","/",730,!0);b&&b()},c||(c="This site uses cookies. By using it, you agree to this."),document.write("<div id=cookie-message>"+c+" <a href='"+a+"'>Learn more</a> <a href='javascript:void(0)' onclick='onCookieConsent()'>Got it</a></div>"))}
function DocumentClickTracker(){var a=this;a.mouseDownTarget=null;a.touchStartData={id:null,target:null};a.callback=null;a.captureEsc=!0;a.start=function(c,b,d){if(null!==a.callback)throw"Cannot execute DocumentClickTracker.start(): already started.";a.captureEsc=void 0!==d?d:!0;a.callback=c;a.ignoredElement=b;document.addEventListener("mousedown",a.onMouseDown,!0);a.captureEsc&&document.addEventListener("keydown",a.onKeyDown,!0);void 0!==document.ontouchstart&&(document.addEventListener("touchstart",
a.onTouchStart,!0),document.addEventListener("touchmove",a.onTouchMove,!0),document.addEventListener("touchend",a.onTouchEnd,!0))};a.stop=function(){null!==a.callback&&(a.callback=null,document.removeEventListener("mousedown",a.onMouseDown,!0),a.captureEsc&&document.removeEventListener("keydown",a.onKeyDown,!0),void 0!==document.ontouchstart&&(document.removeEventListener("touchstart",a.onTouchStart,!0),document.removeEventListener("touchmove",a.onTouchMove,!0),document.removeEventListener("touchend",
a.onTouchEnd,!0)))};a.reset=function(){a.mouseDownTarget=null;a.touchStartData.id=null};a.onMouseDown=function(c){0!==c.button||a.ignoredElement&&a.ignoredElement.contains(c.target)||a.callback(c.target)};a.onTouchStart=function(c){1!=c.touches.length||c.altKey||c.shiftKey||c.ctrlKey||c.metaKey?null!==a.touchStartData.id&&(a.touchStartData.id=null):(a.touchStartData.id=c.changedTouches[0].identifier,a.touchStartData.target=c.target)};a.onTouchMove=function(c){null!==a.touchStartData.id&&1==c.changedTouches.length&&
(a.touchStartData.id=null)};a.onTouchEnd=function(c){0!=c.touches.length||c.altKey||c.shiftKey||c.ctrlKey||c.metaKey||c.changedTouches[0].identifier!=a.touchStartData.id||a.ignoredElement&&a.ignoredElement.contains(c.target)||(a.callback(a.touchStartData.target),a.touchStartData.id=null)};a.onKeyDown=function(c){27!=c.keyCode||c.shiftKey||c.altKey||c.ctrlKey||c.metaKey||a.callback(document)}}
function getViewportHeight(){return window.innerHeight?window.innerHeight:0<document.documentElement.clientHeight?document.documentElement.clientHeight:0<document.body.clientHeight?document.body.clientHeight:!1}function getViewportWidth(){return window.innerWidth?window.innerWidth:0<document.documentElement.clientWidth?document.documentElement.clientWidth:0<document.body.clientWidth?document.body.clientWidth:!1}
function AdUnit(a,c,b){var d=this,e=document.getElementById(a);if(!e)return!1;var f=e.querySelector("ins");if(!f)return!1;var g;d.id=a;d.size=c;d.removed=!1;d.blocked=!1;d.disable=function(){d.removed||d.blocked||(g?g.style.visibility="visible":(g=document.createElement("div"),g.className="ad-banner-blocker",g.style.visibility="visible",g.addEventListener("touchend",function(h){h.preventDefault()},!1),f.appendChild(g)))};d.enable=function(){d.removed||d.blocked||!g||(g.style.visibility="hidden")};
d.remove=function(h){function l(n){if("opacity"==n.propertyName){t.style.display="block";e.style.height=Math.round(e.getBoundingClientRect().height)+"px";n=t.getBoundingClientRect().height;for(var r=e.childNodes.length-1;0<=r;r--)e.childNodes[r]!==t&&e.removeChild(e.childNodes[r]);e.removeEventListener("transitionend",l,!1);e.addEventListener("transitionend",m,!1);e.style.transition="opacity 0.3s linear, height 0.3s linear";e.style.height=Math.ceil(n)+"px";e.style.opacity=""}}function m(n){"height"==
n.propertyName&&(e.classList.add("removed"),b&&b(),e.removeEventListener("transitionend",m,!1))}d.removed=!0;gtag("event","ad_dismissed",{ad_id:d.id+(void 0===d.size?"":"-"+d.size)});var p=d.id.lastIndexOf("-");void 0!==h&&(p=-1<p?d.id.slice(0,p):d.id,setCookie("ab-"+encodeURIComponent(p),"y","",h,!0));var t=e.querySelector(".ad-banner-remove-msg");e.addEventListener("transitionend",l,!1);e.style.transition="opacity 0.2s linear";e.style.opacity="0"};d.reactToAdBlock=function(){if(!d.blocked){d.blocked=
!0;e.classList.add("blocked");var h=e.querySelector(".ad-banner-adblock-msg");h&&(h.style.display="block");e.style.height="auto";if(h=e.querySelector(".remove-ad-link"))h.style.visibility="hidden";b&&b()}}}
var adUnits={map:{},add:function(a,c,b){if(this.map.hasOwnProperty(a))throw"An ad unit with this id is already present";this.map[a]=new AdUnit(a,c,b&&"function"==typeof b?b:void 0)},getUnit:function(a){return this.map[a]},disable:function(){for(var a in this.map)this.map[a].disable()},enable:function(){for(var a in this.map)this.map[a].enable()},checkIfAdsensePresent:function(){if(!window.adsbygoogle)for(var a in this.map)this.map[a].reactToAdBlock()},checkIfAdsLoaded:function(){if(!window.adsbygoogle||
!adsbygoogle.loaded)for(var a in this.map)this.map[a].reactToAdBlock()}};function PlayIndicator(a){var c=this;c.div=a;c.update=function(){c.div.className=tones.playing?"playing "+window.waveType:"stopped "+window.waveType}}function onPlayButtonClick(){tones.playing?(window.playButton.innerHTML="Play",tones.stop()):(window.playButton.innerHTML="Stop",tones.play(window.sliderFreq,window.waveType));window.playIndicator.update()}
function formatNumber(a){a=a.toString().split(".");if(1==a.length)return a[0].toLocaleString("en-US",{style:"currency",useGrouping:!0})+" <small>Hz</small>";if(2==a.length)return 2>=a[1].length?a[0].toLocaleString("en-US")+"<small>."+a[1]+" Hz</small>":"<small>~&thinsp;</small>"+a[0].toLocaleString("en-US")+"<small>."+a[1].slice(0,2)+" Hz</small>"}function separateThousands(a){a=a.toString();for(var c="",b=a.length-1-2;0<b;b-=3)c=","+a.substr(b,3)+c;return c=a.slice(0,b+3)+c}
function formatHertz(a){a=a.toString().split(".");if(1==a.length)return separateThousands(a[0])+" <small>Hz</small>";if(2==a.length){if(2>=a[1].length)return separateThousands(a[0])+"<small>."+a[1]+" Hz</small>";var c="5"<=a[1].charAt(2)?parseInt(a[1].slice(0,2))+1:a[1].slice(0,2);return"<small>~&thinsp;</small>"+separateThousands(a[0])+"<small>."+c+" Hz</small>"}}
function setFreq(a){if(a<MIN_FREQ||a>MAX_FREQ)return!1;if(a==window.sliderFreq)return!0;window.slider_jq.slider("value",freqToSliderPos(a));window.sliderFreq=a;window.freqReadout.update();updateAriaValue();window.noteSelector.updateFromFreq();tones.current.setFreq(window.sliderFreq)}
function setKey(a){if(a<MIN_PIANO_KEY||a>MAX_PIANO_KEY)return!1;window.sliderFreq=440*Math.pow(2,(a-49)/12);window.slider_jq.slider("value",freqToSliderPos(window.sliderFreq));window.freqReadout.update();updateAriaValue();window.noteSelector.displayKey(a);tones.current.setFreq(window.sliderFreq)}function setVolume(a){if(0>a||1<a)return!1;window.volume=a;tones.current.setVolume(window.volume);$(window.volSlider).slider("value",100*a);$("#volume-readout").html(formatPercent(window.volume))}
function setWaveType(a){window.waveType=a;window.waveSelector.update();tones.playing&&window.playIndicator.update();tones.current.setType(a)}function setBalance(a,c){void 0===c&&(c=!0);if(-1>a||1<a)return!1;window.balance=a;tones.current.setBalance(a);window.balanceControl.update(c)}
function moveSliderBy(a){a=window.slider_jq.slider("value")+a;window.slider_jq.slider("option","value",a);window.sliderFreq=sliderPosToFreq(a);window.freqReadout.update();updateAriaValue();window.noteSelector.updateFromFreq();tones.current.setFreq(window.sliderFreq)}function formatPercent(a){return Math.round(100*a).toString()+"%"}function sliderPosToFreq(a){return Math.round(20*Math.pow(1.0025,a)-19)}function freqToSliderPos(a){return Math.round(Math.log((a+19)/20)/Math.log(1.0025))}
function changeFreqBy1Hz(a){1==a?window.setFreq(Math.floor(window.sliderFreq)+a):-1==a&&window.setFreq(Math.ceil(window.sliderFreq)+a)}function changeFreqByHundredthHz(a){1==a?window.setFreq((Math.floor(100*(window.sliderFreq+1E-7))+a)/100):-1==a&&window.setFreq((Math.ceil(100*(window.sliderFreq-1E-7))+a)/100)}function changeFreqByThousandthHz(a){1==a?window.setFreq((Math.floor(1E3*(window.sliderFreq+1E-7))+a)/1E3):-1==a&&window.setFreq((Math.ceil(1E3*(window.sliderFreq-1E-7))+a)/1E3)}
function FrequencyReadout(a){var c=this,b=document.querySelector(a),d,e;if(!b)throw"Cannot find element "+a;a=document.createElement("small");var f=document.createTextNode(""),g=document.createTextNode(""),h=document.createTextNode(""),l=document.createElement("small"),m=document.createTextNode(" Hz");a.appendChild(f);l.appendChild(h);l.appendChild(m);b.appendChild(a);b.appendChild(g);b.appendChild(l);c.tildeOn=!1;c.fractionOn=!1;c.update=function(k){k||(k=3);var q=Math.floor(window.sliderFreq);0<
window.sliderFreq-q?window.sliderFreq.toString().length<=q.toString().length+k+1?(k=q.toString(),g.nodeValue=separateThousands(k),h.nodeValue=window.sliderFreq.toString().slice(k.length),c.fractionOn=!0,f.nodeValue=""):(q=Math.round(window.sliderFreq*Math.pow(10,k))/Math.pow(10,k),g.nodeValue=separateThousands(Math.floor(q).toString()),h.nodeValue=q.toFixed(k).slice(-(k+1)),c.fractionOn=!0,f.nodeValue="~\u2009",c.tildeOn=!0):(g.nodeValue=separateThousands(q.toString()),c.fractionOn&&(h.nodeValue=
""),c.tildeOn&&(f.nodeValue=""))};var p=function(){isNaN(parseFloat(d.value))||window.setFreq(parseFloat(d.value))},t=function(k){isNaN(parseFloat(d.value))||window.setFreq(parseFloat(d.value));c.closeEdit()},n=function(k){if(!(k.shiftKey||k.ctrlKey||k.altKey||k.metaKey))switch(k.keyCode){case 13:c.edit(),k.stopPropagation(),k.preventDefault()}},r=function(k){p();c.closeEdit()},u=function(k){if(!(k.shiftKey||k.ctrlKey||k.altKey||k.metaKey))switch(k.keyCode){case 13:p();break;case 27:c.closeEdit()}};
c.edit=function(){d&&c.destroyEdit();b.classList.add("editing");d=document.createElement("input");d.type="number";d.value=window.sliderFreq.toString();b.onclick=null;b.removeEventListener("keydown",n,!0);b.appendChild(d);d.onchange=p;d.onkeydown=u;d.onblur=r;d.style.opacity="0";d.style.transition="opacity 0.1s linear";reflow(d.clientHeight);d.tabIndex=b.tabIndex;b.tabIndex="";d.focus();d.style.opacity="1";e=new DocumentClickTracker;e.start(t,b,!1)};c.closeEdit=function(){if(!d)return!1;b.tabIndex=
d.tabIndex;d.style.opacity="0";d.addEventListener("transitionend",function(k){"opacity"==k.propertyName&&c.destroyEdit()})};c.destroyEdit=function(){if(!d)return!1;b.classList.remove("editing");b.removeChild(d);d=null;b.onclick=c.edit;b.addEventListener("keydown",n,!0);b.focus();e.stop()};b.onclick=c.edit;b.addEventListener("keydown",n,!0)}
function Dialog(a){var c=this;if(document.getElementById(a))return!1;c.show=function(b,d,e){c.div=document.createElement("div");c.div.id=a;var f=c.div.style;f.position="fixed";f.visibility="hidden";f.opacity="0";if(d.closeButton){var g=document.createElement("button");g.className="close-button";g.appendChild(document.createTextNode("\u00d7"));g.onclick=c.hide;c.div.appendChild(g)}c.div.appendChild(b);document.body.appendChild(c.div);if(d.fullscreen)if(b=c.div.getBoundingClientRect(),f.left=Math.round((getViewportWidth()-
b.width)/2)+"px",void 0===d.fullscreenVertPoint||isNaN(d.fullscreenVertPoint))f.top=Math.round((getViewportHeight()-b.height)/2)+"px";else{g=getViewportHeight();const h=Math.min(b.height/2/g,.5);f.top=Math.round(g*Math.min(Math.max(d.fullscreenVertPoint,h),1-h)-b.height/2)+"px"}reflow(c.div.clientHeight);d.closeOnDocumentClick&&(c.tracker=new DocumentClickTracker,c.tracker.start(c.hide,c.div));f.transition="opacity 0.1s linear";f.visibility="";f.opacity="";c.callback=e;adUnits.disable()};c.hide=function(){if(!c.div)return!1;
c.div.addEventListener("transitionend",function(b){"opacity"==b.propertyName&&c.destroy()});c.div.style.transition="opacity 0.1s linear, visibility 0s linear 0.1s";c.div.style.opacity="0";c.div.style.visibility="hidden";c.tracker&&c.tracker.stop();adUnits.enable();c.callback&&c.callback(Dialog.DIALOG_CLOSE)};c.destroy=function(){document.body.removeChild(c.div);c.div=null}}Dialog.DIALOG_CLOSE=0;
var noteSelectorWindow={panel:null,dialog:null,selectedButton:null,buttonArray:[],callback4NoteSelect:null,callback4WindowClose:null,prepare:function(){var a=document.createElement("table"),c=1<FIRST_C?FIRST_C-12:1,b=FIRST_C-12;do{var d=document.createElement("tr");b+=12;for(c;c<b&&c<=MAX_PIANO_KEY;c++){var e=document.createElement("td"),f=(c-FIRST_C+12)%12;if(1==f||3==f||6==f||8==f||10==f)e.className="halftone";1<=c&&e.appendChild(noteSelectorWindow.createButton(c));d.appendChild(e)}a.appendChild(d)}while(c<=
MAX_PIANO_KEY);noteSelectorWindow.panel=a},createButton:function(a){var c=document.createElement("button"),b=440*Math.pow(2,(a-49)/12);c.value=a;var d=NOTE_NAMES[a].indexOf(" "),e=NOTE_NAMES[a].indexOf("\u2009/");-1==d&&(d=NOTE_NAMES[a].length);-1==e&&(e=NOTE_NAMES[a].length);d=NOTE_NAMES[a].slice(0,Math.min(d,e));b=(b!==Math.floor(b)?"~":"")+b.toFixed(0);c.innerHTML=d+"<small>"+b+"</small>";c.title=NOTE_NAMES[a]+" ("+b+" Hz)";c.onclick=noteSelectorWindow.onButtonClick;return this.buttonArray[a]=
c},onButtonClick:function(a){noteSelectorWindow.selectedButton&&noteSelectorWindow.selectedButton.classList.remove("selected");this.classList.add("selected");noteSelectorWindow.selectedButton=this;noteSelectorWindow.callback4NoteSelect(this.value)},onDialogOutput:function(a){a===Dialog.DIALOG_CLOSE&&noteSelectorWindow.callback4WindowClose()},show:function(a,c){noteSelectorWindow.dialog=new Dialog("note-selector-panel");noteSelectorWindow.dialog.show&&(null==noteSelectorWindow.panel&&noteSelectorWindow.prepare(),
noteSelectorWindow.dialog.show(noteSelectorWindow.panel,{closeButton:!0},noteSelectorWindow.onDialogOutput),noteSelectorWindow.callback4NoteSelect=a,noteSelectorWindow.callback4WindowClose=c,noteSelectorWindow.panel.querySelector("button").focus())},highlightButton:function(a){noteSelectorWindow.selectedButton&&noteSelectorWindow.selectedButton.classList.remove("selected");-1!=a&&(a=noteSelectorWindow.buttonArray[a])&&(a.classList.add("selected"),noteSelectorWindow.selectedButton=a)}};
function NoteSelector(a,c){var b=this;b.button=a;b.windowShown=!1;b.tilde=document.createTextNode("");b.button.appendChild(b.tilde);b.buttonText=document.createTextNode("");b.button.appendChild(b.buttonText);b.button.onclick=function(d){noteSelectorWindow.show(c,function(){b.windowShown=!1;b.button.classList.remove("window-shown")});b.windowShown=!0;b.button.classList.add("window-shown");b.updateFromFreq()};b.updateFromFreq=function(){var d=12*Math.log2(window.sliderFreq/440)+49,e=Math.round(d);e<
MIN_PIANO_KEY?(b.buttonText.nodeValue="below A0",b.tilde.nodeValue=""):e>MAX_PIANO_KEY?(b.buttonText.nodeValue="above "+NOTE_NAMES[MAX_PIANO_KEY],b.tilde.nodeValue=""):(b.buttonText.nodeValue=NOTE_NAMES[e],b.tilde.nodeValue=d==e?"":"~ ",b.windowShown&&noteSelectorWindow.highlightButton(d==e?d:-1))};b.displayKey=function(d){b.buttonText.nodeValue=NOTE_NAMES[d];b.tilde.nodeValue=""}}
function DropDown(a){var c=this;if(document.getElementById(a))return!1;c.show=function(b,d,e){c.div&&c.destroy();c.srcElement=d;c.div=document.createElement("div");c.div.className="drop-down-menu";c.div.id=a;var f=document.createElement("div");f.className="tail";c.div.appendChild(f);var g=d.getBoundingClientRect();d=Math.round((g.left+g.right)/2);var h=c.div.style;h.position="fixed";h.visibility="hidden";h.opacity="0";document.body.appendChild(c.div);c.div.appendChild(b);var l=c.div.getBoundingClientRect(),
m=getViewportWidth();b=Math.round((g.left+g.right-l.width)/2);5>b&&(b=5);b+l.width>m-20&&(b=m-l.width-20);g=Math.round(g.bottom+25);h.left=b+"px";h.top=g+"px";f.style.left=d-b+"px";h.transition="opacity 0.1s linear";h.visibility="";h.opacity="";c.callback=e;c.tracker=new DocumentClickTracker;c.tracker.start(c.onDocumentClick,c.div);adUnits.disable()};c.onDocumentClick=function(b){c.hide()};c.hide=function(){if(!c.div)return!1;c.tracker.stop();c.srcElement.focus();c.div.addEventListener("transitionend",
function(b){"opacity"==b.propertyName&&c.destroy()});c.div.style.transition="opacity 0.1s linear, visibility 0s linear 0.1s";c.div.style.opacity="0";c.div.style.visibility="hidden";adUnits.enable();c.callback&&c.callback(DropDown.DROPDOWN_CLOSE)};c.destroy=function(){document.body.removeChild(c.div);c.div=null;c.callback=null;c.tracker.stop()}}DropDown.DROPDOWN_CLOSE={};
function DropDownMenu(a){var c=this;c.dropDown=new DropDown(a);if(!c.dropDown.show)return!1;c.show=function(b,d,e,f){for(var g=document.createDocumentFragment(),h=0;h<b.length;h++){var l=b[h];l.onclick=c.onOptionClick;l.value==d&&(l.classList.add("selected"),c.selectedButton=l);g.appendChild(l)}c.callback=f;c.dropDown.show(g,e,f);c.dropDown.div.querySelector("button").focus()};c.onOptionClick=function(b){c.selectedButton&&c.selectedButton.classList.remove("selected");c.selectedButton=this;c.selectedButton.classList.add("selected");
c.callback(this.value)}}
function WaveSelector(a,c){var b=this;b.value="";b.button=a;b.menuShown=!1;var d=document.createElement("span");d.className="image-"+b.value;b.button.appendChild(d);var e=[];a=document.createElement("button");a.value="sine";a.tabIndex=b.button.tabIndex+1;var f=document.createElement("span");f.className="image-"+a.value;a.appendChild(f);a.appendChild(document.createTextNode("sine"));e.push(a);a=document.createElement("button");a.value="square";a.tabIndex=b.button.tabIndex+2;f=document.createElement("span");
f.className="image-"+a.value;a.appendChild(f);a.appendChild(document.createTextNode("square"));e.push(a);a=document.createElement("button");a.value="triangle";a.tabIndex=b.button.tabIndex+3;f=document.createElement("span");f.className="image-"+a.value;a.appendChild(f);a.appendChild(document.createTextNode("triangle"));e.push(a);a=document.createElement("button");a.value="sawtooth";a.tabIndex=b.button.tabIndex+4;f=document.createElement("span");f.className="image-"+a.value;a.appendChild(f);a.appendChild(document.createTextNode("sawtooth"));
e.push(a);b.onMenuOutput=function(g){g===DropDown.DROPDOWN_CLOSE?(b.button.classList.remove("control-shown"),b.menuShown=!1):c(g)};b.update=function(){b.value=window.waveType;d.className="image-"+b.value};b.button.onclick=function(g){if(b.menuShown)return!1;g=new DropDownMenu("wave-selector-menu");g.show&&(g.show(e,b.value,this,b.onMenuOutput),b.button.classList.add("control-shown"),b.menuShown=!0)}}
function BalanceControl(a,c){var b=this;b.sliderContainer=null;b.readoutLeftVal=b.readoutRightVal=null;b.button=a;b.shown=!1;b.LspeakerIcon=document.getElementById("balance-control-L-speaker-icon");b.RspeakerIcon=document.getElementById("balance-control-R-speaker-icon");b.onDropDownAction=function(d){d===DropDown.DROPDOWN_CLOSE?(b.button.classList.remove("control-shown"),b.shown=!1):c(d)};b.update=function(d){void 0===d&&(d=!0);var e=Math.min(1,1-window.balance),f=Math.min(1,1+window.balance);b.LspeakerIcon&&
(b.LspeakerIcon.style.opacity=Math.round(100*e)/100);b.RspeakerIcon&&(b.RspeakerIcon.style.opacity=Math.round(100*f)/100);b.shown&&(b.readoutLeftVal.nodeValue=Math.round(100*e)+"%",b.readoutRightVal.nodeValue=Math.round(100*f)+"%",d&&$(b.sliderContainer).slider("value",window.balance))};b.button.onclick=function(d){if(b.shown)return!1;b.dropDown=new DropDown("balance-control-popup");if(!b.dropDown.show)return!1;d=document.createDocumentFragment();var e=document.createElement("div");e.className="balance-button-section";
var f=document.createElement("button");f.className="small-button";var g=f.cloneNode(!0),h=f.cloneNode(!0);f.innerHTML="L";f.value="L";f.title="Left";f.tabIndex=b.button.tabIndex+1;g.innerHTML="C";g.value="C";g.title="Center";g.tabIndex=b.button.tabIndex+2;h.innerHTML="R";h.value="R";h.title="Right";h.tabIndex=b.button.tabIndex+3;f.onclick=g.onclick=h.onclick=b.onLCRButtonClick;e.appendChild(f);e.appendChild(g);e.appendChild(h);d.appendChild(e);e=document.createElementNS("http://www.w3.org/2000/svg",
"svg");e.setAttribute("class","speaker-icon");e.id="left-speaker-icon";f=document.createElementNS("http://www.w3.org/2000/svg","use");f.setAttributeNS("http://www.w3.org/1999/xlink","href","#svg-Lspeaker-icon");e.appendChild(f);d.appendChild(e);b.sliderContainer=document.createElement("span");b.sliderContainer.className="balance-slider";d.appendChild(b.sliderContainer);e=document.createElementNS("http://www.w3.org/2000/svg","svg");e.setAttribute("class","speaker-icon");e.id="right-speaker-icon";f=
document.createElementNS("http://www.w3.org/2000/svg","use");f.setAttributeNS("http://www.w3.org/1999/xlink","href","#svg-Rspeaker-icon");e.appendChild(f);d.appendChild(e);e=document.createElement("div");e.className="balance-readout";f=document.createElement("div");g=document.createElement("span");b.readoutLeftVal=document.createTextNode("");g.appendChild(b.readoutLeftVal);f.appendChild(document.createTextNode("L: "));f.appendChild(g);g=document.createElement("div");h=document.createElement("span");
b.readoutRightVal=document.createTextNode("");h.appendChild(b.readoutRightVal);g.appendChild(document.createTextNode("R: "));g.appendChild(h);e.appendChild(f);e.appendChild(g);d.appendChild(e);$(b.sliderContainer).slider({orientation:"horizontal",range:"min",min:-1,max:1,value:0,step:.01,slide:function(l,m){window.setBalance(m.value,!1)},stop:function(l,m){}});b.sliderContainer.querySelector(".ui-slider-handle").tabIndex=b.button.tabIndex+4;b.shown=!0;b.update();b.dropDown.show(d,this,b.onDropDownAction);
b.dropDown.div.querySelector("button").focus();b.button.classList.add("control-shown")};b.onLCRButtonClick=function(d){switch(d.target.value){case "L":window.setBalance(-1);break;case "C":window.setBalance(0);break;case "R":window.setBalance(1)}}}
function handleKeyDown(a){if(!a.altKey&&!a.metaKey)switch(a.keyCode){case 37:if(a.target!=document.body&&"BUTTON"!=a.target.nodeName&&a.target.parentNode!=window.slider)break;a.preventDefault();a.stopPropagation();a.shiftKey?a.ctrlKey?window.changeFreqByThousandthHz(-1):window.changeFreqBy1Hz(-1):a.ctrlKey?window.changeFreqByHundredthHz(-1):window.moveSliderBy(-1);break;case 39:if(a.target!=document.body&&"BUTTON"!=a.target.nodeName&&a.target.parentNode!=window.slider)break;a.preventDefault();a.stopPropagation();
a.shiftKey?a.ctrlKey?window.changeFreqByThousandthHz(1):window.changeFreqBy1Hz(1):a.ctrlKey?window.changeFreqByHundredthHz(1):window.moveSliderBy(1);break;case 32:a.preventDefault(),onPlayButtonClick()}}function blockSpaceKeyUp(a){a.ctrlKey||a.altKey||a.metaKey||32!=a.keyCode||(a.preventDefault(),a.stopPropagation())}
function UpDownButton(a,c){this.button=document.getElementById(a);if(!this.button)return!1;this.intervalID=this.timeoutID=null;this.action=c;var b=this;this.startRepeatPress=function(){b.action();b.intervalID=setInterval(b.action,80)};this.button.onmousedown=function(d){b.timeoutID||b.intervalID||(b.action(),b.timeoutID=setTimeout(b.startRepeatPress,500),window.addEventListener("mouseup",b.onMouseUp,!0))};this.onMouseUp=function(d){b.timeoutID&&(clearTimeout(b.timeoutID),b.timeoutID=null);b.intervalID&&
(clearInterval(b.intervalID),b.intervalID=null);window.removeEventListener("mouseup",b.onMouseUp)};this.button.ontouchstart=function(d){b.timeoutID||b.intervalID||(d.preventDefault(),b.action(),b.timeoutID=setTimeout(b.startRepeatPress,500))};this.button.ontouchend=function(d){b.timeoutID&&(clearTimeout(b.timeoutID),b.timeoutID=null);b.intervalID&&(clearInterval(b.intervalID),b.intervalID=null);d.preventDefault()};this.button.onkeydown=function(d){if(!(b.timeoutID||b.intervalID||d.shiftKey||d.ctrlKey||
d.altKey||d.metaKey))switch(d.keyCode){case 13:b.action(),d.preventDefault(),d.stopPropagation()}}}
function parseHash(a){var c,b,d;if(""!=a){a=a.split(",");for(let h of a)if(/^\d+\.?\d*$/.test(h)&&void 0===e&&void 0===f)var e=parseFloat(h);else if(/^[A-G]s?\d$/.test(h)&&void 0===f&&void 0===e){h=h.replace("s","\u266f");var f=NOTE_NAMES.findIndex(function(l){return h==l.substr(0,h.length)})}else if(void 0===g&&(d=/^(squ|saw|tri|sin)/.exec(h)))switch(d[0]){case "squ":var g="square";break;case "saw":g="sawtooth";break;case "tri":g="triangle";break;case "sin":g="sine"}else void 0===c&&/^v\d\.?\d*$/.test(h)?
c=parseFloat(h.substr(1)):void 0===b&&/^b-?\d\.?\d*$/.test(h)&&(b=parseFloat(h.substr(1)))}if(void 0===e)e=void 0!==f&&-1!=f?440*Math.pow(2,(f-49)/12):440;else if(e<MIN_FREQ||e>MAX_FREQ)e=440;void 0===g&&(g="sine");if(void 0===c||0>c||1<c)c=DEFAULT_VOLUME;if(void 0===b||-1>b||1<b)b=0;return{freq:e,type:g,vol:c,bal:b}}
function getShortURL(){var a="www."==window.location.hostname.slice(0,4)?window.location.hostname.slice(4):window.location.hostname;return window.location.protocol+"//"+a+"/tone#"+constructHash()}
function constructHash(){var a=12*Math.log2(window.sliderFreq/440)+49;0==a%1&&a>=MIN_PIANO_KEY&&a<=MAX_PIANO_KEY?(a=/^\w\u266f?\d/.exec(NOTE_NAMES[a]),a=null!==a?a[0].replace("\u266f","s"):window.sliderFreq):a=window.sliderFreq;"sine"!=window.waveType&&(a+=","+window.waveType.slice(0,3));a+=",v"+window.volume;0!=window.balance&&(a+=",b"+window.balance);return a}
function setTonePropertiesFromHash(a){a=a?parseHash(a):parseHash(window.location.hash.substr(1));window.setFreq(a.freq);window.setWaveType(a.type);window.setVolume(a.vol);window.setBalance(a.bal)}
function Tone(a,c){var b=this;b.channels=1!==c?2:1;b.playing=!1;b.volume=1;b.balance=0;b.freq=440;b.type="sine";b.oscillator=b.gainNode=b.fadeGainNode=b.mergerNode=b.leftGainNode=b.rightGainNode=null;b.oscillatorStopTimeoutID=null;b.fadeStartTime=0;b.init=function(d,e,f,g){b.gainNode=a.createGain();b.fadeGainNode=a.createGain();2==b.channels&&(b.mergerNode=a.createChannelMerger(2),b.leftGainNode=a.createGain(),b.rightGainNode=a.createGain(),b.leftGainNode.connect(b.mergerNode,0,0),b.rightGainNode.connect(b.mergerNode,
0,1),b.mergerNode.connect(b.gainNode));b.gainNode.connect(b.fadeGainNode);b.fadeGainNode.connect(a.destination);b.freq=d||440;b.type=e||"sine";b.volume=f||1;b.balance=g||0;2==b.channels&&(b.leftGainNode.gain.value=Math.min(1,1-b.balance),b.rightGainNode.gain.value=Math.min(1,1+b.balance));b.gainNode.gain.value=b.volume;b.fadeGainNode.gain.value=0};b.initOscillator=function(){b.oscillator=a.createOscillator();2==b.channels?(b.oscillator.connect(b.leftGainNode),b.oscillator.connect(b.rightGainNode)):
b.oscillator.connect(b.gainNode);b.oscillator.frequency.value=b.freq;b.oscillator.type=b.type};b.play=function(d){void 0===d&&(d=a.currentTime);if(b.oscillatorStopTimeoutID)clearTimeout(b.oscillatorStopTimeoutID),b.oscillatorStopTimeoutID=null;else{if(b.playing)return!1;b.initOscillator();b.oscillator.start(d)}BrowserDetect.Firefox?b.fadeGainNode.gain.setTargetAtTime(1,d,FADE_SET_TARGET_TIME_CONSTANT):(b.fadeGainNode.gain.cancelScheduledValues(d),b.fadeGainNode.gain.setValueAtTime(b.fadeGainNode.gain.value,
d),b.fadeGainNode.gain.linearRampToValueAtTime(1,d+FADE_TIME*(1-b.fadeGainNode.gain.value)));b.playing=!0};b.stop=function(d){if(!b.playing)return!1;void 0===d&&(d=a.currentTime);if(BrowserDetect.Firefox)b.fadeGainNode.gain.setTargetAtTime(0,d,FADE_SET_TARGET_TIME_CONSTANT),d=1E3*(d-a.currentTime+8*FADE_SET_TARGET_TIME_CONSTANT);else{b.fadeGainNode.gain.cancelScheduledValues(d);b.fadeGainNode.gain.setValueAtTime(b.fadeGainNode.gain.value,d);var e=FADE_TIME*b.fadeGainNode.gain.value;b.fadeGainNode.gain.linearRampToValueAtTime(0,
d+e);d=1E3*(d-a.currentTime+e+.5)}b.oscillatorStopTimeoutID=setTimeout(function(){b.oscillator.stop();b.oscillatorStopTimeoutID=null;b.playing=!1},d)};b.setFreq=function(d){b.freq=d;b.playing&&b.oscillator.frequency.setTargetAtTime(d,a.currentTime,.03)};b.setType=function(d){b.type=d;b.playing&&(b.oscillator.type=d)};b.setBalance=function(d){if(2!==b.channels)return!1;b.balance=d;b.playing?(b.leftGainNode.gain.setTargetAtTime(Math.min(1,1-d),a.currentTime,FADE_SET_TARGET_TIME_CONSTANT),b.rightGainNode.gain.setTargetAtTime(Math.min(1,
1+d),a.currentTime,FADE_SET_TARGET_TIME_CONSTANT)):(b.leftGainNode.gain.setValueAtTime(Math.min(1,1-d),a.currentTime),b.rightGainNode.gain.setValueAtTime(Math.min(1,1+d),a.currentTime))};b.setVolume=function(d){b.playing?b.gainNode.gain.setTargetAtTime(d,a.currentTime,FADE_SET_TARGET_TIME_CONSTANT):b.gainNode.gain.setValueAtTime(d,a.currentTime);b.volume=d}}
var tones={array:[],current:null,playing:!1,init:function(){if(window.AudioContext)tones.context=new AudioContext;else if(window.webkitAudioContext)tones.context=new webkitAudioContext;else throw"Cannot initialize AudioContext";},add:function(){tones.current=new Tone(tones.context);tones.current.init();tones.array.push(tones.current)},remove:function(a){if(!tones.array[a])return!1;for(a+=1;a<tones.array[length];a++)tones.array[a-1]=tones.array[a];--tones.array.length},select:function(a){if(!tones.array[a])return!1;
tones.current=tones.array[a]},play:function(){tones.playing=!0;"suspended"==tones.context.state&&tones.context.resume();for(var a=0;a<tones.array.length;a++)tones.array[a].play()},stop:function(){tones.playing=!1;for(var a=0;a<tones.array.length;a++)tones.array[a].stop()}};function updateAriaValue(){window.sliderHandle.setAttribute("aria-valuenow",window.sliderFreq)}document.addEventListener?document.addEventListener("DOMContentLoaded",init,!1):window.onload=init;
window.addEventListener("load",onLoad,!1);loadCookies();
function init(){if(void 0===window.AudioContext&&void 0===window.webkitAudioContext||void 0===Math.log2){var a=document.createElement("div");a.id="browser-warning";a.innerHTML="The Online Tone Generator won\u2019t work because your browser does not fully support the Web Audio API. You can use the Online Tone Generator if you install a recent version of Firefox, Chrome or Safari.";document.body.appendChild(a)}document.addEventListener("keydown",handleKeyDown,!0);window.slider=document.getElementById("slider");
window.volSlider=document.getElementById("volume-slider");$("#slider").slider({orientation:"horizontal",range:"min",min:0,max:2770,value:440,step:1,slide:function(b,d){window.sliderFreq=sliderPosToFreq(d.value);window.freqReadout.update();updateAriaValue();window.noteSelector.updateFromFreq();tones.current.setFreq(window.sliderFreq)},stop:function(b,d){}});$("#volume-slider").slider({orientation:"horizontal",range:"min",min:0,max:100,value:100,step:1,slide:function(b,d){window.volume=d.value/100;
$("#volume-readout").html(formatPercent(window.volume));tones.current.setVolume(window.volume)},stop:function(b,d){}});window.sliderHandle=document.querySelector("#slider .ui-slider-handle");sliderHandle&&(sliderHandle.tabIndex=20,sliderHandle.setAttribute("role","slider"));if(a=document.querySelector("#volume-slider .ui-slider-handle"))a.tabIndex=30;window.playButton=document.getElementById("play-button");window.playButton.onclick=onPlayButtonClick;new UpDownButton("freq-up-button",function(){window.changeFreqBy1Hz(1)});
new UpDownButton("freq-down-button",function(){window.changeFreqBy1Hz(-1)});a=document.getElementById("octave-up-button");var c=document.getElementById("octave-down-button");a.onclick=function(){window.setFreq(2*window.sliderFreq)};c.onclick=function(){window.setFreq(window.sliderFreq/2)};window.slider_jq=$("#slider");window.freqReadout=new FrequencyReadout("#freq-readout");window.playIndicator=new PlayIndicator(document.getElementById("play-indicator"));window.balanceControl=new BalanceControl(document.getElementById("balance-control"),
window.setBalance);window.noteSelector=new NoteSelector(document.getElementById("note-selector"),window.setKey);window.waveSelector=new WaveSelector(document.getElementById("wave-selector"),window.setWaveType);window.getLinkButton=document.getElementById("get-link");window.getLinkButton.onclick=function(){var b=new DropDown("notice");navigator.clipboard.writeText(getShortURL()).then(function(){b.show(document.createTextNode("Link to current tone copied"),window.getLinkButton)},function(){b.show(document.createTextNode("Error: Could not copy link to clipboard"),
window.getLinkButton)})};tones.init();tones.add();setTonePropertiesFromHash();window.playButton=document.getElementById("play-button");window.playButton.addEventListener("keyup",blockSpaceKeyUp);AD_FREE||adUnits.checkIfAdsensePresent()}function onLoad(){AD_FREE||adUnits.checkIfAdsLoaded()};
